backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "home"
    label: "Home"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - label: Template key
            name: templateKey
            widget: hidden
            default: home
          - label: "Diary"
            name: "diary"
            widget: "list"
            fields:
              - label: Title
                name: title
                widget: string
                required: true
              - label: Date
                name: date
                widget: datetime
                required: false
              - label: Place
                name: place
                widget: object
                fields:
                  - label: Position
                    name: position
                    widget: map
                    required: false
                  - label: Name
                    name: name
                    widget: string
              - label: Images
                name: images
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Image Name
                    name: name
                    widget: string
                    required: false
              - label: Description
                name: description
                widget: text

  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    slug: "{{title}}"
    create: false
    filter:
      field: temmplateKey
      value: other
    fields:
      - label: Template key
        name: templateKey
        widget: hidden
        default: other
      - label: "Title"
        name: title
        widget: string
        required: true
