backend:
  use_large_media_transforms_in_media_library: false
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "home"
    label: "Diary"
    folder: "src/pages/diary"
    create: true
    slug: "{{title}}"
    files:
      fields:
        - label: Template key
          name: templateKey
          widget: hidden
          default: home
        - label: Title
          name: title
          widget: string
          required: false
        - label: Date
          name: date
          widget: datetime
          required: false
        - label: Place
          name: place
          widget: object
          required: false
          fields:
            - label: Position
              name: position
              widget: map
              required: false
            - label: Name
              name: name
              widget: string
              required: false
        - label: Images
          name: images
          widget: list
          required: false
          fields:
            - label: Image
              name: image
              widget: image
              required: false
            - label: Image Name
              name: name
              widget: string
              required: false
        - label: Description
          name: description
          widget: text
          required: false

  - name: "pages"
    label: "Pages"
    folder: "src/pages/pages"
    slug: "{{title}}"
    create: true
    filter:
      field: temmplateKey
      value: other
    fields:
      - label: Template key
        name: templateKey
        widget: hidden
        default: other
      - label: "Title"
        name: title
        widget: string
        required: true
